project:
  type: website
  output-dir: docs
  resources:
    - files/CV_IvanMARIN.pdf

website:
  title: "Ivan Marin"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Research"
        href: research.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



