project:
  type: website
  output-dir: docs
  resources:
    - files/CV_IvanMARIN.pdf

website:
  title: "Ivan Marin"
  site-url: "https://www.elcontrafactual.fr"
  repo-url: https://github.com/iamarin/iamarin.github.io
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Research"
        href: research.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



